export const servicesData = [
  {
    id: 1,
    name: "Sale Deed Registration",
    category: "Property Registration",
    description: "Register property ownership legally.",
    procedure: ["Prepare deed", "Verify documents", "Pay stamp duty", "Register"],
    documents: ["Aadhar", "PAN", "Sale Agreement"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 2,
    name: "Gift Deed Registration",
    category: "Property Registration",
    description: "Transfer property as gift.",
    procedure: ["Draft deed", "Verify", "Register"],
    documents: ["Aadhar", "Gift Deed"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 3,
    name: "Property Transfer",
    category: "Property Registration",
    description: "Transfer ownership officially.",
    procedure: ["Apply", "Verify", "Transfer"],
    documents: ["Sale Deed", "ID Proof"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 4,
    name: "Khata Transfer",
    category: "Khata & Ownership",
    description: "Transfer municipal records.",
    procedure: ["Apply", "Verify", "Update"],
    documents: ["Tax Receipt", "Sale Deed"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 5,
    name: "Khata Extraction",
    category: "Khata & Ownership",
    description: "Get Khata certificate.",
    procedure: ["Apply", "Verification", "Issue"],
    documents: ["Property Details"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 6,
    name: "Ownership Change",
    category: "Khata & Ownership",
    description: "Update ownership records.",
    procedure: ["Submit request", "Verify", "Update"],
    documents: ["Sale Deed"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 7,
    name: "Building Plan Approval",
    category: "Construction Approval",
    description: "Approval before construction.",
    procedure: ["Submit plan", "Inspection", "Approval"],
    documents: ["Plan", "Ownership Proof"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 8,
    name: "Construction License",
    category: "Construction Approval",
    description: "License for construction.",
    procedure: ["Apply", "Verify", "Approve"],
    documents: ["Plan", "ID"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 9,
    name: "Land Conversion",
    category: "Land & Layout",
    description: "Convert land usage.",
    procedure: ["Apply", "Verify", "Approve"],
    documents: ["Land Docs"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 10,
    name: "Layout Approval",
    category: "Land & Layout",
    description: "Approval for layout.",
    procedure: ["Submit plan", "Verify", "Approve"],
    documents: ["Layout Plan"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 11,
    name: "Title Verification",
    category: "Legal & Verification",
    description: "Verify ownership legally.",
    procedure: ["Apply", "Verify records"],
    documents: ["Property Docs"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 12,
    name: "Legal Opinion",
    category: "Legal & Verification",
    description: "Legal advice for property.",
    procedure: ["Submit details", "Get report"],
    documents: ["Property Docs"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 13,
    name: "Encumbrance Certificate",
    category: "Legal & Verification",
    description: "Check legal dues.",
    procedure: ["Apply", "Search", "Issue"],
    documents: ["Property Details"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 14,
    name: "Home Loan Assistance",
    category: "Home Buyer Support",
    description: "Help for loan processing.",
    procedure: ["Apply", "Verify", "Assist"],
    documents: ["Income Proof"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 15,
    name: "Property Valuation",
    category: "Home Buyer Support",
    description: "Know property value.",
    procedure: ["Request", "Inspect", "Report"],
    documents: ["Property Docs"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 16,
    name: "Site Inspection",
    category: "Home Buyer Support",
    description: "Inspection before buying.",
    procedure: ["Request", "Visit", "Report"],
    documents: ["Property Details"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 17,
    name: "Agricultural Land Registration",
    category: "Farm Land",
    description: "Register farm land.",
    procedure: ["Apply", "Verify", "Register"],
    documents: ["Land Docs"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 18,
    name: "Conversion Guidance",
    category: "Farm Land",
    description: "Guide for land conversion.",
    procedure: ["Consult", "Apply"],
    documents: ["Land Docs"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 19,
    name: "Document Checklist",
    category: "Document Guidance",
    description: "Know required documents.",
    procedure: ["Select service", "Get list"],
    documents: ["None"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
  {
    id: 20,
    name: "Application Filing Help",
    category: "Document Guidance",
    description: "Help filling applications.",
    procedure: ["Submit info", "Get help"],
    documents: ["Form Details"],
    agentCommission: "3%",
    platformFee: "₹499",
  },
];